#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VaBank.UI.Web.Views
{
    
    #line 3 "..\..\Views\Index.cshtml"
    using System;
    
    #line default
    #line hidden
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class Index : RazorGenerator.Templating.RazorTemplateBase
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");



WriteLiteral("\r\n");


WriteLiteral("<html>\r\n    <head>\r\n        <title>VaBank</title>\r\n    </head>\r\n    <body>\r\n     " +
"   <h1>Hello, World!</h1>\r\n        Current time: ");


            
            #line 10 "..\..\Views\Index.cshtml"
                 Write(DateTime.Now);

            
            #line default
            #line hidden
WriteLiteral("\r\n    </body>\r\n</html>\r\n");


        }
    }
}
#pragma warning restore 1591
