-- generated by dbdsgnr.appspot.com

CREATE TABLE [User](
  [UserID] [UNIQUEIDENTIFIER],
  [PasswordHash] [NVARCHAR](128),
  [SecurityStamp] [NVARCHAR](128),
  [LockoutEnabled] [BIT],
  [LockoutEndDateUtc] [DATETIME](0),
  [AccessFailedCount] [INT],
  [UserName] [NVARCHAR](128),
  CONSTRAINT [PK_USER] PRIMARY KEY CLUSTERED
  (
  [UserID] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)
)
GO
CREATE TABLE [UserProfile](
  [UserID] [UNIQUEIDENTIFIER],
  [FirstName] [NVARCHAR](128),
  [LastName] [NVARCHAR](128),
  [Email] [NVARCHAR](128),
  [PhoneNumber] [NVARCHAR](128),
  [PhoneNumberConfirmed] [BIT],
  [TwoFactorEnabled] [BIT]
)
GO
CREATE TABLE [UserClaim](
  [UserID] [UNIQUEIDENTIFIER],
  [Type] [NVARCHAR](128),
  [Value] [NVARCHAR](128)
)
GO
CREATE TABLE [ApplicationClient](
  [ID] [UNIQUEIDENTIFIER],
  [Name] [NVARCHAR](128),
  [Active] [BIT],
  [RefreshTokenLifeTime] [INT],
  [ApplicationType] [TINYINT],
  [AllowedOrigin] [NVARCHAR](128),
  CONSTRAINT [PK_APPLICATIONCLIENT] PRIMARY KEY CLUSTERED
  (
  [ID] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)
)
GO
CREATE TABLE [ApplicationToken](
  [ID] [UNIQUEIDENTIFIER],
  [ClientID] [UNIQUEIDENTIFIER],
  [IssuedUtc] [DATETIME](0),
  [ExpiresUtc] [DATETIME](0),
  [ProtectedTicket] [NVARCHAR](128),
  CONSTRAINT [PK_APPLICATIONTOKEN] PRIMARY KEY CLUSTERED
  (
  [ID] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)
)
GO

ALTER TABLE [UserProfile] WITH CHECK ADD CONSTRAINT [UserProfile_fk1] FOREIGN KEY ([UserID]) REFERENCES [User]([UserID])
ON UPDATE CASCADE
GO
ALTER TABLE [UserProfile] CHECK CONSTRAINT [UserProfile_fk1]
GO

ALTER TABLE [UserClaim] WITH CHECK ADD CONSTRAINT [UserClaim_fk1] FOREIGN KEY ([UserID]) REFERENCES [User]([UserID])
ON UPDATE CASCADE
GO
ALTER TABLE [UserClaim] CHECK CONSTRAINT [UserClaim_fk1]
GO


ALTER TABLE [ApplicationToken] WITH CHECK ADD CONSTRAINT [ApplicationToken_fk1] FOREIGN KEY ([ClientID]) REFERENCES [ApplicationClient]([ID])
ON UPDATE CASCADE
GO
ALTER TABLE [ApplicationToken] CHECK CONSTRAINT [ApplicationToken_fk1]
GO
